AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    fac22654-2e8d-43fc-a1f5-4f82922f6c31:
      size:
        width: 60
        height: 60
      position:
        x: 331
        'y': 121
      z: 0
Parameters:
  InstanceTypeParameter:
    Type: 'String'
    Default: 't2.micro'
    AllowedValues:
      - 't2.micro'
      - 't2.medium'
      - 't3.micro'
    Description: 'Enter t2.micro, t2.medium, or t3.micro. Default is t2.micro.'
  VPCID:
    Type: 'AWS::EC2::VPC::Id'
Resources:
  EC2I3CSLN:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: 'us-east-1a'
      InstanceType: 
        Ref: InstanceTypeParameter
      ImageId: 'ami-0022f774911c1d690'
      Tags:
        - Key: "Name"
          Value: "ec2-with-some-config"
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      KeyName: ram
      UserData: 
        Fn::Base64: 
          !Sub | 
            #!/bin/bash
            mkdir web 
            cd web 
            touch post.{1..5}.txt
      Volumes:
        - Device: xvdb
          VolumeId: !Ref rpt04appvolume
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: 
        Ref: VPCID
      SecurityGroupIngress:
        - Description: 'Allow all inboud traffic'
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - Description: 'Allow all outbound traffic'
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
  rpt04appvolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      AvailabilityZone: 'us-east-1a'
      Size: 20
      VolumeType: gp2
      Tags:
        - Key: Name
          Value: 'attach-volume'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: fac22654-2e8d-43fc-a1f5-4f82922f6c31
